### ISSUE TITLE
Проверка тестовой задачи

### ISSUE THREAD

**Issue by gebvlad** [4rtis/Test#1]
1. Некорректно отрабатывает на строке `)(`
2. Остальное корректно 
3. Отсутствуют дополнительные задачи 2 и 3

**Comment by 4rtis** [comment]
Внёс корректировки, всё работает корректно.
https://github.com/4rtis/Test/blob/main/%D0%A1%D0%BA%D0%BE%D0%B1%D0%BA%D0%B8%20C%23(2).cs
